CREATE TABLE "dahuang-wvp-pro"."GEN_TABLE"
(
"TABLE_ID" BIGINT AUTO_INCREMENT NOT NULL,
"TABLE_NAME" VARCHAR(200 CHAR) DEFAULT '',
"TABLE_COMMENT" VARCHAR(500 CHAR) DEFAULT '',
"SUB_TABLE_NAME" VARCHAR(64 CHAR),
"SUB_TABLE_FK_NAME" VARCHAR(64 CHAR),
"CLASS_NAME" VARCHAR(100 CHAR) DEFAULT '',
"TPL_CATEGORY" VARCHAR(200 CHAR) DEFAULT 'crud',
"TPL_WEB_TYPE" VARCHAR(30 CHAR) DEFAULT '',
"PACKAGE_NAME" VARCHAR(100 CHAR),
"MODULE_NAME" VARCHAR(30 CHAR),
"BUSINESS_NAME" VARCHAR(30 CHAR),
"FUNCTION_NAME" VARCHAR(50 CHAR),
"FUNCTION_AUTHOR" VARCHAR(50 CHAR),
"GEN_TYPE" CHAR(1 CHAR) DEFAULT '0',
"GEN_PATH" VARCHAR(200 CHAR) DEFAULT '/',
"OPTIONS" VARCHAR(1000 CHAR),
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR),
NOT CLUSTER PRIMARY KEY("TABLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

COMMENT ON TABLE "dahuang-wvp-pro".GEN_TABLE IS '代码生成业务表';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."BUSINESS_NAME" IS '生成业务名';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."CLASS_NAME" IS '实体类名称';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."FUNCTION_AUTHOR" IS '生成功能作者';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."FUNCTION_NAME" IS '生成功能名';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."GEN_PATH" IS '生成路径（不填默认项目路径）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."GEN_TYPE" IS '生成代码方式（0zip压缩包 1自定义路径）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."MODULE_NAME" IS '生成模块名';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."OPTIONS" IS '其它生成选项';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."PACKAGE_NAME" IS '生成包路径';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."SUB_TABLE_FK_NAME" IS '子表关联的外键名';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."SUB_TABLE_NAME" IS '关联子表的表名';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."TABLE_COMMENT" IS '表描述';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."TABLE_ID" IS '编号';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."TABLE_NAME" IS '表名称';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."TPL_CATEGORY" IS '使用的模板（crud单表操作 tree树表操作）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."TPL_WEB_TYPE" IS '前端模板类型（element-ui模版 element-plus模版）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."GEN_TABLE_COLUMN"
(
"COLUMN_ID" BIGINT AUTO_INCREMENT NOT NULL,
"TABLE_ID" BIGINT,
"COLUMN_NAME" VARCHAR(200 CHAR),
"COLUMN_COMMENT" VARCHAR(500 CHAR),
"COLUMN_TYPE" VARCHAR(100 CHAR),
"JAVA_TYPE" VARCHAR(500 CHAR),
"JAVA_FIELD" VARCHAR(200 CHAR),
"IS_PK" CHAR(1 CHAR),
"IS_INCREMENT" CHAR(1 CHAR),
"IS_REQUIRED" CHAR(1 CHAR),
"IS_INSERT" CHAR(1 CHAR),
"IS_EDIT" CHAR(1 CHAR),
"IS_LIST" CHAR(1 CHAR),
"IS_QUERY" CHAR(1 CHAR),
"QUERY_TYPE" VARCHAR(200 CHAR) DEFAULT 'EQ',
"HTML_TYPE" VARCHAR(200 CHAR),
"DICT_TYPE" VARCHAR(200 CHAR) DEFAULT '',
"SORT" INT,
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("COLUMN_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

COMMENT ON TABLE "dahuang-wvp-pro".GEN_TABLE_COLUMN IS '代码生成业务表字段';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."COLUMN_COMMENT" IS '列描述';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."COLUMN_ID" IS '编号';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."COLUMN_NAME" IS '列名称';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."COLUMN_TYPE" IS '列类型';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."HTML_TYPE" IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."IS_EDIT" IS '是否编辑字段（1是）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."IS_INCREMENT" IS '是否自增（1是）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."IS_INSERT" IS '是否为插入字段（1是）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."IS_LIST" IS '是否列表字段（1是）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."IS_PK" IS '是否主键（1是）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."IS_QUERY" IS '是否查询字段（1是）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."IS_REQUIRED" IS '是否必填（1是）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."JAVA_FIELD" IS 'JAVA字段名';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."JAVA_TYPE" IS 'JAVA类型';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."QUERY_TYPE" IS '查询方式（等于、不等于、大于、小于、范围）';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."SORT" IS '排序';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."TABLE_ID" IS '归属表编号';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".GEN_TABLE_COLUMN."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_BLOB_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"TRIGGER_NAME" VARCHAR(200 CHAR) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200 CHAR) NOT NULL,
"BLOB_DATA" BLOB,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_BLOB_TRIGGERS IS 'Blob类型的触发器表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_BLOB_TRIGGERS."BLOB_DATA" IS '存放持久化Trigger对象';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_BLOB_TRIGGERS."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_BLOB_TRIGGERS."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_BLOB_TRIGGERS."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_CALENDARS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"CALENDAR_NAME" VARCHAR(200 CHAR) NOT NULL,
"CALENDAR" BLOB NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "CALENDAR_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_CALENDARS IS '日历信息表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_CALENDARS."CALENDAR" IS '存放持久化calendar对象';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_CALENDARS."CALENDAR_NAME" IS '日历名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_CALENDARS."SCHED_NAME" IS '调度名称';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_CRON_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"TRIGGER_NAME" VARCHAR(200 CHAR) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200 CHAR) NOT NULL,
"CRON_EXPRESSION" VARCHAR(200 CHAR) NOT NULL,
"TIME_ZONE_ID" VARCHAR(80 CHAR),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_CRON_TRIGGERS IS 'Cron类型的触发器表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_CRON_TRIGGERS."CRON_EXPRESSION" IS 'cron表达式';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_CRON_TRIGGERS."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_CRON_TRIGGERS."TIME_ZONE_ID" IS '时区';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_CRON_TRIGGERS."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_CRON_TRIGGERS."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_FIRED_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"ENTRY_ID" VARCHAR(95 CHAR) NOT NULL,
"TRIGGER_NAME" VARCHAR(200 CHAR) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200 CHAR) NOT NULL,
"INSTANCE_NAME" VARCHAR(200 CHAR) NOT NULL,
"FIRED_TIME" BIGINT NOT NULL,
"SCHED_TIME" BIGINT NOT NULL,
"PRIORITY" INT NOT NULL,
"STATE" VARCHAR(16 CHAR) NOT NULL,
"JOB_NAME" VARCHAR(200 CHAR),
"JOB_GROUP" VARCHAR(200 CHAR),
"IS_NONCONCURRENT" VARCHAR(1 CHAR),
"REQUESTS_RECOVERY" VARCHAR(1 CHAR),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "ENTRY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS IS '已触发的触发器表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."ENTRY_ID" IS '调度器实例id';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."FIRED_TIME" IS '触发的时间';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."INSTANCE_NAME" IS '调度器实例名';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."IS_NONCONCURRENT" IS '是否并发';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."PRIORITY" IS '优先级';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."REQUESTS_RECOVERY" IS '是否接受恢复执行';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."SCHED_TIME" IS '定时器制定的时间';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."STATE" IS '状态';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_FIRED_TRIGGERS."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_JOB_DETAILS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"JOB_NAME" VARCHAR(200 CHAR) NOT NULL,
"JOB_GROUP" VARCHAR(200 CHAR) NOT NULL,
"DESCRIPTION" VARCHAR(250 CHAR),
"JOB_CLASS_NAME" VARCHAR(250 CHAR) NOT NULL,
"IS_DURABLE" VARCHAR(1 CHAR) NOT NULL,
"IS_NONCONCURRENT" VARCHAR(1 CHAR) NOT NULL,
"IS_UPDATE_DATA" VARCHAR(1 CHAR) NOT NULL,
"REQUESTS_RECOVERY" VARCHAR(1 CHAR) NOT NULL,
"JOB_DATA" BLOB,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_JOB_DETAILS IS '任务详细信息表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."DESCRIPTION" IS '相关介绍';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."IS_DURABLE" IS '是否持久化';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."IS_NONCONCURRENT" IS '是否并发';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."IS_UPDATE_DATA" IS '是否更新数据';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."JOB_CLASS_NAME" IS '执行任务类名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."JOB_DATA" IS '存放持久化job对象';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."REQUESTS_RECOVERY" IS '是否接受恢复执行';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_JOB_DETAILS."SCHED_NAME" IS '调度名称';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_LOCKS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"LOCK_NAME" VARCHAR(40 CHAR) NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "LOCK_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_LOCKS IS '存储的悲观锁信息表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_LOCKS."LOCK_NAME" IS '悲观锁名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_LOCKS."SCHED_NAME" IS '调度名称';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_PAUSED_TRIGGER_GRPS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200 CHAR) NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_PAUSED_TRIGGER_GRPS IS '暂停的触发器表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_PAUSED_TRIGGER_GRPS."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_PAUSED_TRIGGER_GRPS."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_SCHEDULER_STATE"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"INSTANCE_NAME" VARCHAR(200 CHAR) NOT NULL,
"LAST_CHECKIN_TIME" BIGINT NOT NULL,
"CHECKIN_INTERVAL" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "INSTANCE_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_SCHEDULER_STATE IS '调度器状态表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SCHEDULER_STATE."CHECKIN_INTERVAL" IS '检查间隔时间';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SCHEDULER_STATE."INSTANCE_NAME" IS '实例名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SCHEDULER_STATE."LAST_CHECKIN_TIME" IS '上次检查时间';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SCHEDULER_STATE."SCHED_NAME" IS '调度名称';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_SIMPLE_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"TRIGGER_NAME" VARCHAR(200 CHAR) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200 CHAR) NOT NULL,
"REPEAT_COUNT" BIGINT NOT NULL,
"REPEAT_INTERVAL" BIGINT NOT NULL,
"TIMES_TRIGGERED" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_SIMPLE_TRIGGERS IS '简单触发器的信息表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPLE_TRIGGERS."REPEAT_COUNT" IS '重复的次数统计';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPLE_TRIGGERS."REPEAT_INTERVAL" IS '重复的间隔时间';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPLE_TRIGGERS."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPLE_TRIGGERS."TIMES_TRIGGERED" IS '已经触发的次数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPLE_TRIGGERS."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPLE_TRIGGERS."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_SIMPROP_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"TRIGGER_NAME" VARCHAR(200 CHAR) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200 CHAR) NOT NULL,
"STR_PROP_1" VARCHAR(512 CHAR),
"STR_PROP_2" VARCHAR(512 CHAR),
"STR_PROP_3" VARCHAR(512 CHAR),
"INT_PROP_1" INT,
"INT_PROP_2" INT,
"LONG_PROP_1" BIGINT,
"LONG_PROP_2" BIGINT,
"DEC_PROP_1" DECIMAL(13,4),
"DEC_PROP_2" DECIMAL(13,4),
"BOOL_PROP_1" VARCHAR(1 CHAR),
"BOOL_PROP_2" VARCHAR(1 CHAR),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS IS '同步机制的行锁表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."BOOL_PROP_1" IS 'Boolean类型的trigger的第一个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."BOOL_PROP_2" IS 'Boolean类型的trigger的第二个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."DEC_PROP_1" IS 'decimal类型的trigger的第一个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."DEC_PROP_2" IS 'decimal类型的trigger的第二个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."INT_PROP_1" IS 'int类型的trigger的第一个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."INT_PROP_2" IS 'int类型的trigger的第二个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."LONG_PROP_1" IS 'long类型的trigger的第一个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."LONG_PROP_2" IS 'long类型的trigger的第二个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."STR_PROP_1" IS 'String类型的trigger的第一个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."STR_PROP_2" IS 'String类型的trigger的第二个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."STR_PROP_3" IS 'String类型的trigger的第三个参数';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_SIMPROP_TRIGGERS."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE TABLE "dahuang-wvp-pro"."QRTZ_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120 CHAR) NOT NULL,
"TRIGGER_NAME" VARCHAR(200 CHAR) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200 CHAR) NOT NULL,
"JOB_NAME" VARCHAR(200 CHAR) NOT NULL,
"JOB_GROUP" VARCHAR(200 CHAR) NOT NULL,
"DESCRIPTION" VARCHAR(250 CHAR),
"NEXT_FIRE_TIME" BIGINT,
"PREV_FIRE_TIME" BIGINT,
"PRIORITY" INT,
"TRIGGER_STATE" VARCHAR(16 CHAR) NOT NULL,
"TRIGGER_TYPE" VARCHAR(8 CHAR) NOT NULL,
"START_TIME" BIGINT NOT NULL,
"END_TIME" BIGINT,
"CALENDAR_NAME" VARCHAR(200 CHAR),
"MISFIRE_INSTR" SMALLINT,
"JOB_DATA" BLOB,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".QRTZ_TRIGGERS IS '触发器详细信息表';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."CALENDAR_NAME" IS '日程表名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."DESCRIPTION" IS '相关介绍';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."END_TIME" IS '结束时间';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."JOB_DATA" IS '存放持久化job对象';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."JOB_GROUP" IS 'qrtz_job_details表job_group的外键';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."JOB_NAME" IS 'qrtz_job_details表job_name的外键';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."MISFIRE_INSTR" IS '补偿执行的策略';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."NEXT_FIRE_TIME" IS '上一次触发时间（毫秒）';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."PREV_FIRE_TIME" IS '下一次触发时间（默认为-1表示不触发）';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."PRIORITY" IS '优先级';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."START_TIME" IS '开始时间';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."TRIGGER_GROUP" IS '触发器所属组的名字';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."TRIGGER_NAME" IS '触发器的名字';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."TRIGGER_STATE" IS '触发器状态';
COMMENT ON COLUMN "dahuang-wvp-pro".QRTZ_TRIGGERS."TRIGGER_TYPE" IS '触发器的类型';


CREATE OR REPLACE INDEX "dahuang-wvp-pro"."SCHED_NAME" ON "dahuang-wvp-pro"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"JOB_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR)  WITHOUT CLU_REC_ADDR ;

CREATE TABLE "dahuang-wvp-pro"."SYS_BASE_CONFIG"
(
"CONFIG_ID" INT AUTO_INCREMENT NOT NULL,
"SSL_ENABLED" CHAR(1 CHAR) DEFAULT '0',
"SSL_KEY_STORE" VARCHAR(255 CHAR) DEFAULT '',
"SSL_KEY_STORE_PASSWORD" VARCHAR(255 CHAR),
"SSL_PORT" INT,
"HTTP_PORT" VARCHAR(255 CHAR),
"ACCESS_DOMAIN" VARCHAR(255 CHAR),
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR),
NOT CLUSTER PRIMARY KEY("CONFIG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 2;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_BASE_CONFIG IS '基础配置表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."ACCESS_DOMAIN" IS '访问域名';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."CONFIG_ID" IS '配置主键';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."HTTP_PORT" IS 'http端口';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."SSL_ENABLED" IS '是否开启HTTPS（0关闭 1开启）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."SSL_KEY_STORE" IS '证书路径';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."SSL_KEY_STORE_PASSWORD" IS '证书密码';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."SSL_PORT" IS 'HTTPS端口';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_BASE_CONFIG."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_CONFIG"
(
"CONFIG_ID" INT AUTO_INCREMENT NOT NULL,
"CONFIG_NAME" VARCHAR(100 CHAR) DEFAULT '',
"CONFIG_KEY" VARCHAR(100 CHAR) DEFAULT '',
"CONFIG_VALUE" VARCHAR(500 CHAR) DEFAULT '',
"CONFIG_TYPE" CHAR(1 CHAR) DEFAULT 'N',
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR),
NOT CLUSTER PRIMARY KEY("CONFIG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 24;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_CONFIG IS '参数配置表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."CONFIG_ID" IS '参数主键';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."CONFIG_KEY" IS '参数键名';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."CONFIG_NAME" IS '参数名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."CONFIG_TYPE" IS '系统内置（Y是 N否）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."CONFIG_VALUE" IS '参数键值';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_CONFIG."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_DEPT"
(
"DEPT_ID" BIGINT AUTO_INCREMENT NOT NULL,
"PARENT_ID" BIGINT DEFAULT 0,
"ANCESTORS" VARCHAR(50 CHAR) DEFAULT '',
"DEPT_NAME" VARCHAR(30 CHAR) DEFAULT '',
"ORDER_NUM" INT DEFAULT 0,
"LEADER" VARCHAR(20 CHAR),
"PHONE" VARCHAR(11 CHAR),
"EMAIL" VARCHAR(50 CHAR),
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"DEL_FLAG" CHAR(1 CHAR) DEFAULT '0',
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("DEPT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 110;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_DEPT IS '部门表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."ANCESTORS" IS '祖级列表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."DEPT_ID" IS '部门id';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."DEPT_NAME" IS '部门名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."EMAIL" IS '邮箱';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."LEADER" IS '负责人';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."ORDER_NUM" IS '显示顺序';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."PARENT_ID" IS '父部门id';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."PHONE" IS '联系电话';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."STATUS" IS '部门状态（0正常 1停用）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DEPT."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_DICT_DATA"
(
"DICT_CODE" BIGINT AUTO_INCREMENT NOT NULL,
"DICT_SORT" INT DEFAULT 0,
"DICT_LABEL" VARCHAR(100 CHAR) DEFAULT '',
"DICT_VALUE" VARCHAR(100 CHAR) DEFAULT '',
"DICT_TYPE" VARCHAR(100 CHAR) DEFAULT '',
"CSS_CLASS" VARCHAR(100 CHAR),
"LIST_CLASS" VARCHAR(100 CHAR),
"IS_DEFAULT" CHAR(1 CHAR) DEFAULT 'N',
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR),
NOT CLUSTER PRIMARY KEY("DICT_CODE")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 62;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_DICT_DATA IS '字典数据表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."CSS_CLASS" IS '样式属性（其他样式扩展）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."DICT_CODE" IS '字典编码';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."DICT_LABEL" IS '字典标签';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."DICT_SORT" IS '字典排序';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."DICT_VALUE" IS '字典键值';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."IS_DEFAULT" IS '是否默认（Y是 N否）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."LIST_CLASS" IS '表格回显样式';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_DATA."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_DICT_TYPE"
(
"DICT_ID" BIGINT AUTO_INCREMENT NOT NULL,
"DICT_NAME" VARCHAR(100 CHAR) DEFAULT '',
"DICT_TYPE" VARCHAR(100 CHAR) DEFAULT '',
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR),
NOT CLUSTER PRIMARY KEY("DICT_ID"),
CONSTRAINT "DICT_TYPE" UNIQUE("DICT_TYPE")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 21;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_DICT_TYPE IS '字典类型表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."DICT_ID" IS '字典主键';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."DICT_NAME" IS '字典名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_DICT_TYPE."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_JOB"
(
"JOB_ID" BIGINT AUTO_INCREMENT NOT NULL,
"JOB_NAME" VARCHAR(64 CHAR) DEFAULT '' NOT NULL,
"JOB_GROUP" VARCHAR(64 CHAR) DEFAULT 'DEFAULT' NOT NULL,
"INVOKE_TARGET" VARCHAR(500 CHAR) NOT NULL,
"CRON_EXPRESSION" VARCHAR(255 CHAR) DEFAULT '',
"MISFIRE_POLICY" VARCHAR(20 CHAR) DEFAULT '3',
"CONCURRENT" CHAR(1 CHAR) DEFAULT '1',
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR) DEFAULT '',
NOT CLUSTER PRIMARY KEY("JOB_ID", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 6;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_JOB IS '定时任务调度表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."CONCURRENT" IS '是否并发执行（0允许 1禁止）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."CRON_EXPRESSION" IS 'cron执行表达式';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."INVOKE_TARGET" IS '调用目标字符串';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."JOB_ID" IS '任务ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."MISFIRE_POLICY" IS '计划执行错误策略（1立即执行 2执行一次 3放弃执行）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."REMARK" IS '备注信息';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."STATUS" IS '状态（0正常 1暂停）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_JOB_LOG"
(
"JOB_LOG_ID" BIGINT AUTO_INCREMENT NOT NULL,
"JOB_NAME" VARCHAR(64 CHAR) NOT NULL,
"JOB_GROUP" VARCHAR(64 CHAR) NOT NULL,
"INVOKE_TARGET" VARCHAR(500 CHAR) NOT NULL,
"JOB_MESSAGE" VARCHAR(500 CHAR),
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"EXCEPTION_INFO" VARCHAR(2000 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("JOB_LOG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 5;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_JOB_LOG IS '定时任务调度日志表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB_LOG."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB_LOG."EXCEPTION_INFO" IS '异常信息';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB_LOG."INVOKE_TARGET" IS '调用目标字符串';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB_LOG."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB_LOG."JOB_LOG_ID" IS '任务日志ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB_LOG."JOB_MESSAGE" IS '日志信息';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB_LOG."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_JOB_LOG."STATUS" IS '执行状态（0正常 1失败）';


CREATE TABLE "dahuang-wvp-pro"."SYS_LOGININFOR"
(
"INFO_ID" BIGINT AUTO_INCREMENT NOT NULL,
"USER_NAME" VARCHAR(50 CHAR) DEFAULT '',
"IPADDR" VARCHAR(128 CHAR) DEFAULT '',
"LOGIN_LOCATION" VARCHAR(255 CHAR) DEFAULT '',
"BROWSER" VARCHAR(50 CHAR) DEFAULT '',
"OS" VARCHAR(50 CHAR) DEFAULT '',
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"MSG" VARCHAR(255 CHAR) DEFAULT '',
"LOGIN_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("INFO_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 781;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_LOGININFOR IS '系统访问记录';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."BROWSER" IS '浏览器类型';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."INFO_ID" IS '访问ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."IPADDR" IS '登录IP地址';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."LOGIN_LOCATION" IS '登录地点';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."LOGIN_TIME" IS '访问时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."MSG" IS '提示消息';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."OS" IS '操作系统';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."STATUS" IS '登录状态（0成功 1失败）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_LOGININFOR."USER_NAME" IS '用户账号';


CREATE OR REPLACE INDEX "dahuang-wvp-pro"."IDX_SYS_LOGININFOR_S" ON "dahuang-wvp-pro"."SYS_LOGININFOR"("STATUS" ASC) STORAGE(ON "MAIN", CLUSTERBTR)  WITHOUT CLU_REC_ADDR ;
CREATE OR REPLACE INDEX "dahuang-wvp-pro"."IDX_SYS_LOGININFOR_LT" ON "dahuang-wvp-pro"."SYS_LOGININFOR"("LOGIN_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR)  WITHOUT CLU_REC_ADDR ;

CREATE TABLE "dahuang-wvp-pro"."SYS_MENU"
(
"MENU_ID" BIGINT AUTO_INCREMENT NOT NULL,
"MENU_NAME" VARCHAR(50 CHAR) NOT NULL,
"PARENT_ID" BIGINT DEFAULT 0,
"ORDER_NUM" INT DEFAULT 0,
"PATH" VARCHAR(200 CHAR) DEFAULT '',
"COMPONENT" VARCHAR(255 CHAR),
"QUERY" VARCHAR(255 CHAR),
"ROUTE_NAME" VARCHAR(50 CHAR) DEFAULT '',
"IS_FRAME" INT DEFAULT 1,
"IS_CACHE" INT DEFAULT 0,
"MENU_TYPE" CHAR(1 CHAR) DEFAULT '',
"VISIBLE" CHAR(1 CHAR) DEFAULT '0',
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"PERMS" VARCHAR(100 CHAR),
"ICON" VARCHAR(100 CHAR) DEFAULT '#',
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR) DEFAULT '',
NOT CLUSTER PRIMARY KEY("MENU_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 2163;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_MENU IS '菜单权限表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."COMPONENT" IS '组件路径';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."ICON" IS '菜单图标';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."IS_CACHE" IS '是否缓存（0缓存 1不缓存）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."IS_FRAME" IS '是否为外链（0是 1否）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."MENU_NAME" IS '菜单名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."MENU_TYPE" IS '菜单类型（M目录 C菜单 F按钮）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."ORDER_NUM" IS '显示顺序';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."PARENT_ID" IS '父菜单ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."PATH" IS '路由地址';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."PERMS" IS '权限标识';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."QUERY" IS '路由参数';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."ROUTE_NAME" IS '路由名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."STATUS" IS '菜单状态（0正常 1停用）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_MENU."VISIBLE" IS '菜单状态（0显示 1隐藏）';


CREATE TABLE "dahuang-wvp-pro"."SYS_NOTICE"
(
"NOTICE_ID" INT AUTO_INCREMENT NOT NULL,
"NOTICE_TITLE" VARCHAR(50 CHAR) NOT NULL,
"NOTICE_TYPE" CHAR(1 CHAR) NOT NULL,
"NOTICE_CONTENT" BLOB,
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(255 CHAR),
NOT CLUSTER PRIMARY KEY("NOTICE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 3;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_NOTICE IS '通知公告表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."NOTICE_CONTENT" IS '公告内容';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."NOTICE_ID" IS '公告ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."NOTICE_TITLE" IS '公告标题';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."NOTICE_TYPE" IS '公告类型（1通知 2公告）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."STATUS" IS '公告状态（0正常 1关闭）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_NOTICE."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_OPER_LOG"
(
"OPER_ID" BIGINT AUTO_INCREMENT NOT NULL,
"TITLE" VARCHAR(50 CHAR) DEFAULT '',
"BUSINESS_TYPE" INT DEFAULT 0,
"METHOD" VARCHAR(200 CHAR) DEFAULT '',
"REQUEST_METHOD" VARCHAR(10 CHAR) DEFAULT '',
"OPERATOR_TYPE" INT DEFAULT 0,
"OPER_NAME" VARCHAR(50 CHAR) DEFAULT '',
"DEPT_NAME" VARCHAR(50 CHAR) DEFAULT '',
"OPER_URL" VARCHAR(255 CHAR) DEFAULT '',
"OPER_IP" VARCHAR(128 CHAR) DEFAULT '',
"OPER_LOCATION" VARCHAR(255 CHAR) DEFAULT '',
"OPER_PARAM" VARCHAR(2000 CHAR) DEFAULT '',
"JSON_RESULT" VARCHAR(2000 CHAR) DEFAULT '',
"STATUS" INT DEFAULT 0,
"ERROR_MSG" VARCHAR(2000 CHAR) DEFAULT '',
"OPER_TIME" TIMESTAMP(0),
"COST_TIME" BIGINT DEFAULT 0,
NOT CLUSTER PRIMARY KEY("OPER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 2114;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_OPER_LOG IS '操作日志记录';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."BUSINESS_TYPE" IS '业务类型（0其它 1新增 2修改 3删除）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."COST_TIME" IS '消耗时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."DEPT_NAME" IS '部门名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."ERROR_MSG" IS '错误消息';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."JSON_RESULT" IS '返回参数';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."METHOD" IS '方法名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."OPERATOR_TYPE" IS '操作类别（0其它 1后台用户 2手机端用户）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."OPER_ID" IS '日志主键';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."OPER_IP" IS '主机地址';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."OPER_LOCATION" IS '操作地点';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."OPER_NAME" IS '操作人员';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."OPER_PARAM" IS '请求参数';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."OPER_TIME" IS '操作时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."OPER_URL" IS '请求URL';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."REQUEST_METHOD" IS '请求方式';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."STATUS" IS '操作状态（0正常 1异常）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_OPER_LOG."TITLE" IS '模块标题';


CREATE OR REPLACE INDEX "dahuang-wvp-pro"."IDX_SYS_OPER_LOG_S" ON "dahuang-wvp-pro"."SYS_OPER_LOG"("STATUS" ASC) STORAGE(ON "MAIN", CLUSTERBTR)  WITHOUT CLU_REC_ADDR ;
CREATE OR REPLACE INDEX "dahuang-wvp-pro"."IDX_SYS_OPER_LOG_OT" ON "dahuang-wvp-pro"."SYS_OPER_LOG"("OPER_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR)  WITHOUT CLU_REC_ADDR ;
CREATE OR REPLACE INDEX "dahuang-wvp-pro"."IDX_SYS_OPER_LOG_BT" ON "dahuang-wvp-pro"."SYS_OPER_LOG"("BUSINESS_TYPE" ASC) STORAGE(ON "MAIN", CLUSTERBTR)  WITHOUT CLU_REC_ADDR ;

CREATE TABLE "dahuang-wvp-pro"."SYS_POST"
(
"POST_ID" BIGINT AUTO_INCREMENT NOT NULL,
"POST_CODE" VARCHAR(64 CHAR) NOT NULL,
"POST_NAME" VARCHAR(50 CHAR) NOT NULL,
"POST_SORT" INT NOT NULL,
"STATUS" CHAR(1 CHAR) NOT NULL,
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR),
NOT CLUSTER PRIMARY KEY("POST_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 6;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_POST IS '岗位信息表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."POST_CODE" IS '岗位编码';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."POST_ID" IS '岗位ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."POST_NAME" IS '岗位名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."POST_SORT" IS '显示顺序';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_POST."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_ROLE"
(
"ROLE_ID" BIGINT AUTO_INCREMENT NOT NULL,
"ROLE_NAME" VARCHAR(30 CHAR) NOT NULL,
"ROLE_KEY" VARCHAR(100 CHAR) NOT NULL,
"ROLE_SORT" INT NOT NULL,
"DATA_SCOPE" CHAR(1 CHAR) DEFAULT '1',
"MENU_CHECK_STRICTLY" TINYINT DEFAULT 1,
"DEPT_CHECK_STRICTLY" TINYINT DEFAULT 1,
"STATUS" CHAR(1 CHAR) NOT NULL,
"DEL_FLAG" CHAR(1 CHAR) DEFAULT '0',
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR),
NOT CLUSTER PRIMARY KEY("ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 4;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_ROLE IS '角色信息表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."DATA_SCOPE" IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."DEPT_CHECK_STRICTLY" IS '部门树选择项是否关联显示';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."MENU_CHECK_STRICTLY" IS '菜单树选择项是否关联显示';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."ROLE_KEY" IS '角色权限字符串';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."ROLE_SORT" IS '显示顺序';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."STATUS" IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."SYS_ROLE_DEPT"
(
"ROLE_ID" BIGINT NOT NULL,
"DEPT_ID" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("ROLE_ID", "DEPT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_ROLE_DEPT IS '角色和部门关联表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE_DEPT."DEPT_ID" IS '部门ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE_DEPT."ROLE_ID" IS '角色ID';


CREATE TABLE "dahuang-wvp-pro"."SYS_ROLE_MENU"
(
"ROLE_ID" BIGINT NOT NULL,
"MENU_ID" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("ROLE_ID", "MENU_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_ROLE_MENU IS '角色和菜单关联表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE_MENU."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_ROLE_MENU."ROLE_ID" IS '角色ID';


CREATE TABLE "dahuang-wvp-pro"."SYS_USER"
(
"USER_ID" BIGINT AUTO_INCREMENT NOT NULL,
"DEPT_ID" BIGINT,
"USER_NAME" VARCHAR(30 CHAR) NOT NULL,
"NICK_NAME" VARCHAR(30 CHAR) NOT NULL,
"USER_TYPE" VARCHAR(2 CHAR) DEFAULT '00',
"EMAIL" VARCHAR(50 CHAR) DEFAULT '',
"PHONENUMBER" VARCHAR(11 CHAR) DEFAULT '',
"SEX" CHAR(1 CHAR) DEFAULT '0',
"AVATAR" VARCHAR(100 CHAR) DEFAULT '',
"PASSWORD" VARCHAR(100 CHAR) DEFAULT '',
"STATUS" CHAR(1 CHAR) DEFAULT '0',
"DEL_FLAG" CHAR(1 CHAR) DEFAULT '0',
"LOGIN_IP" VARCHAR(128 CHAR) DEFAULT '',
"LOGIN_DATE" TIMESTAMP(0),
"PUSH_KEY" VARCHAR(50 CHAR),
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR),
NOT CLUSTER PRIMARY KEY("USER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 6;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_USER IS '用户信息表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."AVATAR" IS '头像地址';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."DEPT_ID" IS '部门ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."EMAIL" IS '用户邮箱';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."LOGIN_DATE" IS '最后登录时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."LOGIN_IP" IS '最后登录IP';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."NICK_NAME" IS '用户昵称';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."PASSWORD" IS '密码';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."PHONENUMBER" IS '手机号码';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."SEX" IS '用户性别（0男 1女 2未知）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."STATUS" IS '帐号状态（0正常 1停用）';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."USER_ID" IS '用户ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."USER_NAME" IS '用户账号';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER."USER_TYPE" IS '用户类型（00系统用户）';


CREATE TABLE "dahuang-wvp-pro"."SYS_USER_CHANNEL"
(
"USER_ID" BIGINT NOT NULL,
"CHANNEL_ID" VARCHAR(64 CHAR) NOT NULL,
"DEVICE_ID" VARCHAR(255 CHAR),
NOT CLUSTER PRIMARY KEY("USER_ID", "CHANNEL_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "dahuang-wvp-pro"."SYS_USER_POST"
(
"USER_ID" BIGINT NOT NULL,
"POST_ID" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("USER_ID", "POST_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_USER_POST IS '用户与岗位关联表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER_POST."POST_ID" IS '岗位ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER_POST."USER_ID" IS '用户ID';


CREATE TABLE "dahuang-wvp-pro"."SYS_USER_ROLE"
(
"USER_ID" BIGINT NOT NULL,
"ROLE_ID" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("USER_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".SYS_USER_ROLE IS '用户和角色关联表';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER_ROLE."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "dahuang-wvp-pro".SYS_USER_ROLE."USER_ID" IS '用户ID';


CREATE TABLE "dahuang-wvp-pro"."WVP_CLOUD_RECORD"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"APP" VARCHAR(255 CHAR),
"STREAM" VARCHAR(255 CHAR),
"CALL_ID" VARCHAR(255 CHAR),
"START_TIME" BIGINT,
"END_TIME" BIGINT,
"MEDIA_SERVER_ID" VARCHAR(50 CHAR),
"FILE_NAME" VARCHAR(255 CHAR),
"FOLDER" VARCHAR(500 CHAR),
"FILE_PATH" VARCHAR(500 CHAR),
"COLLECT" TINYINT DEFAULT 0,
"FILE_SIZE" BIGINT,
"TIME_LEN" BIGINT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 284;

CREATE TABLE "dahuang-wvp-pro"."WVP_COMMON_GROUP"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"DEVICE_ID" VARCHAR(50 CHAR) NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"PARENT_ID" INT,
"PARENT_DEVICE_ID" VARCHAR(50 CHAR),
"BUSINESS_GROUP" VARCHAR(50 CHAR) NOT NULL,
"CREATE_TIME" VARCHAR(50 CHAR) NOT NULL,
"UPDATE_TIME" VARCHAR(50 CHAR) NOT NULL,
"CIVIL_CODE" VARCHAR(50 CHAR),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_COMMON_GROUP_DEVICE_PLATFORM" UNIQUE("DEVICE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 6;

CREATE TABLE "dahuang-wvp-pro"."WVP_COMMON_REGION"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"DEVICE_ID" VARCHAR(50 CHAR) NOT NULL,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"PARENT_ID" INT,
"PARENT_DEVICE_ID" VARCHAR(50 CHAR),
"CREATE_TIME" VARCHAR(50 CHAR) NOT NULL,
"UPDATE_TIME" VARCHAR(50 CHAR) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_COMMON_REGION_DEVICE_ID" UNIQUE("DEVICE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 7;

CREATE TABLE "dahuang-wvp-pro"."WVP_DEVICE"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"DEPT_ID" BIGINT,
"DEVICE_ID" VARCHAR(50 CHAR) NOT NULL,
"NAME" VARCHAR(255 CHAR),
"MANUFACTURER" VARCHAR(255 CHAR),
"DB_MODEL" VARCHAR(255 CHAR),
"FIRMWARE" VARCHAR(255 CHAR),
"TRANSPORT" VARCHAR(50 CHAR),
"STREAM_MODE" VARCHAR(50 CHAR),
"ON_LINE" TINYINT DEFAULT 0,
"REGISTER_TIME" VARCHAR(50 CHAR),
"KEEPALIVE_TIME" VARCHAR(50 CHAR),
"IP" VARCHAR(50 CHAR),
"CREATE_TIME" VARCHAR(50 CHAR),
"UPDATE_TIME" VARCHAR(50 CHAR),
"PORT" INT,
"EXPIRES" INT,
"SUBSCRIBE_CYCLE_FOR_CATALOG" INT DEFAULT 0,
"SUBSCRIBE_CYCLE_FOR_MOBILE_POSITION" INT DEFAULT 0,
"MOBILE_POSITION_SUBMISSION_INTERVAL" INT DEFAULT 5,
"SUBSCRIBE_CYCLE_FOR_ALARM" INT DEFAULT 0,
"HOST_ADDRESS" VARCHAR(50 CHAR),
"CHARSET" VARCHAR(50 CHAR),
"SSRC_CHECK" TINYINT DEFAULT 0,
"GEO_COORD_SYS" VARCHAR(50 CHAR),
"MEDIA_SERVER_ID" VARCHAR(50 CHAR) DEFAULT 'auto',
"CUSTOM_NAME" VARCHAR(255 CHAR),
"SDP_IP" VARCHAR(50 CHAR),
"LOCAL_IP" VARCHAR(50 CHAR),
"PASSWORD" VARCHAR(255 CHAR),
"AS_MESSAGE_CHANNEL" TINYINT DEFAULT 0,
"HEART_BEAT_INTERVAL" INT,
"HEART_BEAT_COUNT" INT,
"POSITION_CAPABILITY" INT,
"BROADCAST_PUSH_AFTER_ACK" TINYINT DEFAULT 0,
"LAT" VARCHAR(30 CHAR),
"LNG" VARCHAR(30 CHAR),
"ADDRESS_MAP" VARCHAR(255 CHAR),
"PROTOCOL_TYPE" VARCHAR(50 CHAR) DEFAULT 'GB28181',
"SRC_URL" VARCHAR(255 CHAR),
"STREAM_TYPE" VARCHAR(50 CHAR) DEFAULT 'default',
"FFMPEG_CMD_KEY" VARCHAR(255 CHAR),
"RTSP_TYPE" VARCHAR(50 CHAR) DEFAULT '0',
"ENABLE_AUDIO" TINYINT DEFAULT 0,
"ENABLE_MP4" TINYINT DEFAULT 0,
"ENABLE_REMOVE_NONE_READER" TINYINT DEFAULT 0,
"ENABLE_DISABLE_NONE_READER" TINYINT DEFAULT 0,
"STREAM_KEY" VARCHAR(255 CHAR),
"START_OFFLINE_PUSH" TINYINT,
"PUSHING" TINYINT DEFAULT 0,
"PUSH_TIME" VARCHAR(50 CHAR),
"USER_NAME" VARCHAR(255 CHAR),
"ONVIF_AUTH_TYPE" VARCHAR(255 CHAR),
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"REMARK" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_DEVICE_DEVICE" UNIQUE("DEVICE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 220;

COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."ADDRESS_MAP" IS '地图定位地址';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."DEPT_ID" IS '部门ID';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."ENABLE_AUDIO" IS '是否启用音频';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."ENABLE_DISABLE_NONE_READER" IS '无人观看时自动停用';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."ENABLE_MP4" IS '是否启用录像';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."ENABLE_REMOVE_NONE_READER" IS '无人观看时自动移除';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."FFMPEG_CMD_KEY" IS 'ffmpeg模板KEY';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."LAT" IS '纬度';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."LNG" IS '经度';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."ONVIF_AUTH_TYPE" IS 'onvif 设备鉴权方式';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."PROTOCOL_TYPE" IS '设备接入协议类型';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."RTSP_TYPE" IS 'RTSP拉流方式';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."SRC_URL" IS '拉流源地址';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."STREAM_KEY" IS 'ZLM返回的streamKey';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."STREAM_TYPE" IS '代理类型';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE."USER_NAME" IS '用户名';


CREATE TABLE "dahuang-wvp-pro"."WVP_DEVICE_ALARM"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"DEVICE_ID" VARCHAR(50 CHAR) NOT NULL,
"CHANNEL_ID" VARCHAR(50 CHAR) NOT NULL,
"ALARM_PRIORITY" VARCHAR(50 CHAR),
"ALARM_METHOD" VARCHAR(50 CHAR),
"ALARM_TIME" VARCHAR(50 CHAR),
"ALARM_DESCRIPTION" VARCHAR(255 CHAR),
"LONGITUDE" DOUBLE,
"LATITUDE" DOUBLE,
"ALARM_TYPE" VARCHAR(50 CHAR),
"CREATE_TIME" VARCHAR(50 CHAR) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE TABLE "dahuang-wvp-pro"."WVP_DEVICE_CHANNEL"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"DEVICE_ID" VARCHAR(50 CHAR),
"NAME" VARCHAR(255 CHAR),
"MANUFACTURER" VARCHAR(50 CHAR),
"DB_MODEL" VARCHAR(50 CHAR),
"OWNER" VARCHAR(50 CHAR),
"CIVIL_CODE" VARCHAR(50 CHAR),
"BLOCK" VARCHAR(50 CHAR),
"ADDRESS" VARCHAR(50 CHAR),
"PARENTAL" INT,
"PARENT_ID" VARCHAR(50 CHAR),
"SAFETY_WAY" INT,
"REGISTER_WAY" INT,
"CERT_NUM" VARCHAR(50 CHAR),
"CERTIFIABLE" INT,
"ERR_CODE" INT,
"END_TIME" VARCHAR(50 CHAR),
"SECRECY" INT,
"IP_ADDRESS" VARCHAR(50 CHAR),
"PORT" INT,
"PASSWORD" VARCHAR(255 CHAR),
"STATUS" VARCHAR(50 CHAR) DEFAULT 'OFF',
"LONGITUDE" DOUBLE,
"LATITUDE" DOUBLE,
"PTZ_TYPE" INT,
"POSITION_TYPE" INT,
"ROOM_TYPE" INT,
"USE_TYPE" INT,
"SUPPLY_LIGHT_TYPE" INT,
"DIRECTION_TYPE" INT,
"RESOLUTION" VARCHAR(255 CHAR),
"BUSINESS_GROUP_ID" VARCHAR(255 CHAR),
"DOWNLOAD_SPEED" VARCHAR(255 CHAR),
"SVC_SPACE_SUPPORT_MOD" INT,
"SVC_TIME_SUPPORT_MODE" INT,
"CREATE_TIME" VARCHAR(50 CHAR) NOT NULL,
"UPDATE_TIME" VARCHAR(50 CHAR) NOT NULL,
"SUB_COUNT" INT,
"STREAM_ID" VARCHAR(255 CHAR),
"HAS_AUDIO" TINYINT DEFAULT 0,
"GPS_TIME" VARCHAR(50 CHAR),
"STREAM_IDENTIFICATION" VARCHAR(50 CHAR),
"CHANNEL_TYPE" INT DEFAULT 0 NOT NULL,
"GB_DEVICE_ID" VARCHAR(50 CHAR),
"GB_NAME" VARCHAR(255 CHAR),
"GB_MANUFACTURER" VARCHAR(255 CHAR),
"GB_MODEL" VARCHAR(255 CHAR),
"GB_OWNER" VARCHAR(255 CHAR),
"GB_CIVIL_CODE" VARCHAR(255 CHAR),
"GB_BLOCK" VARCHAR(255 CHAR),
"GB_ADDRESS" VARCHAR(255 CHAR),
"GB_PARENTAL" INT,
"GB_PARENT_ID" VARCHAR(255 CHAR),
"GB_SAFETY_WAY" INT,
"GB_REGISTER_WAY" INT,
"GB_CERT_NUM" VARCHAR(50 CHAR),
"GB_CERTIFIABLE" INT,
"GB_ERR_CODE" INT,
"GB_END_TIME" VARCHAR(50 CHAR),
"GB_SECRECY" INT,
"GB_IP_ADDRESS" VARCHAR(50 CHAR),
"GB_PORT" INT,
"GB_PASSWORD" VARCHAR(50 CHAR),
"GB_STATUS" VARCHAR(50 CHAR),
"GB_LONGITUDE" DOUBLE,
"GB_LATITUDE" DOUBLE,
"GB_BUSINESS_GROUP_ID" VARCHAR(50 CHAR),
"GB_PTZ_TYPE" INT,
"GB_POSITION_TYPE" INT,
"GB_ROOM_TYPE" INT,
"GB_USE_TYPE" INT,
"GB_SUPPLY_LIGHT_TYPE" INT,
"GB_DIRECTION_TYPE" INT,
"GB_RESOLUTION" VARCHAR(255 CHAR),
"GB_DOWNLOAD_SPEED" VARCHAR(255 CHAR),
"GB_SVC_SPACE_SUPPORT_MOD" INT,
"GB_SVC_TIME_SUPPORT_MODE" INT,
"RECORD_PLAN_ID" INT,
"DATA_TYPE" INT NOT NULL,
"DATA_DEVICE_ID" INT NOT NULL,
"CHANNEL_NO" VARCHAR(255 CHAR),
"SRC_URL" VARCHAR(1000 CHAR),
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"REMARK" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 290;

COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE_CHANNEL."CHANNEL_NO" IS '通道号';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_DEVICE_CHANNEL."SRC_URL" IS '推流地址';


CREATE TABLE "dahuang-wvp-pro"."WVP_DEVICE_MOBILE_POSITION"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"DEVICE_ID" VARCHAR(50 CHAR) NOT NULL,
"CHANNEL_ID" VARCHAR(50 CHAR) NOT NULL,
"DEVICE_NAME" VARCHAR(255 CHAR),
"TIME" VARCHAR(50 CHAR),
"LONGITUDE" DOUBLE,
"LATITUDE" DOUBLE,
"ALTITUDE" DOUBLE,
"SPEED" DOUBLE,
"DIRECTION" DOUBLE,
"REPORT_SOURCE" VARCHAR(50 CHAR),
"CREATE_TIME" VARCHAR(50 CHAR),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE TABLE "dahuang-wvp-pro"."WVP_FAVORITES"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"FAVORITES_NAME" VARCHAR(30 CHAR),
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR) DEFAULT '',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 3;

COMMENT ON TABLE "dahuang-wvp-pro".WVP_FAVORITES IS '国标通道收藏表';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES."FAVORITES_NAME" IS '收藏夹名称';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES."ID" IS 'id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."WVP_FAVORITES_CHANNEL"
(
"CHANNEL_ID" BIGINT NOT NULL,
"FAVORITES_ID" BIGINT,
"GB_NAME" VARCHAR(100 CHAR),
"GB_PARENTID" VARCHAR(100 CHAR),
"GB_DEVICEID" VARCHAR(100 CHAR),
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR) DEFAULT '',
NOT CLUSTER PRIMARY KEY("CHANNEL_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL IS '收藏夹国标通道表';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."CHANNEL_ID" IS '国标通道id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."FAVORITES_ID" IS '收藏夹id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."GB_DEVICEID" IS '通道id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."GB_NAME" IS '通道名称';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."GB_PARENTID" IS '设备id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_FAVORITES_CHANNEL."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."WVP_MARK"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"MARK_NAME" VARCHAR(30 CHAR),
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR) DEFAULT '',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 3;

COMMENT ON TABLE "dahuang-wvp-pro".WVP_MARK IS 'wvp通道标记表';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK."ID" IS 'id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK."MARK_NAME" IS '标记照片';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."WVP_MARK_CHANNEL"
(
"CHANNEL_ID" BIGINT NOT NULL,
"MARK_ID" BIGINT,
"GB_NAME" VARCHAR(100 CHAR),
"GB_PARENTID" VARCHAR(100 CHAR),
"GB_DEVICEID" VARCHAR(100 CHAR),
"CREATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64 CHAR) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500 CHAR) DEFAULT '',
NOT CLUSTER PRIMARY KEY("CHANNEL_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "dahuang-wvp-pro".WVP_MARK_CHANNEL IS 'wvp国标通道标记表';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."CHANNEL_ID" IS '国标通道id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."GB_DEVICEID" IS '通道id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."GB_NAME" IS '通道名称';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."GB_PARENTID" IS '设备id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."MARK_ID" IS '标记id';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."REMARK" IS '备注';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_MARK_CHANNEL."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."WVP_MEDIA_SERVER"
(
"ID" VARCHAR(255 CHAR) NOT NULL,
"IP" VARCHAR(50 CHAR),
"HOOK_IP" VARCHAR(50 CHAR),
"SDP_IP" VARCHAR(50 CHAR),
"STREAM_IP" VARCHAR(50 CHAR),
"HTTP_PORT" INT,
"HTTP_SSL_PORT" INT,
"RTMP_PORT" INT,
"RTMP_SSL_PORT" INT,
"RTP_PROXY_PORT" INT,
"RTSP_PORT" INT,
"RTSP_SSL_PORT" INT,
"FLV_PORT" INT,
"FLV_SSL_PORT" INT,
"WS_FLV_PORT" INT,
"WS_FLV_SSL_PORT" INT,
"AUTO_CONFIG" TINYINT DEFAULT 0,
"SECRET" VARCHAR(50 CHAR),
"TYPE" VARCHAR(50 CHAR) DEFAULT 'zlm',
"RTP_ENABLE" TINYINT DEFAULT 0,
"RTP_PORT_RANGE" VARCHAR(50 CHAR),
"SEND_RTP_PORT_RANGE" VARCHAR(50 CHAR),
"RECORD_ASSIST_PORT" INT,
"DEFAULT_SERVER" TINYINT DEFAULT 0,
"CREATE_TIME" VARCHAR(50 CHAR),
"UPDATE_TIME" VARCHAR(50 CHAR),
"HOOK_ALIVE_INTERVAL" INT,
"RECORD_PATH" VARCHAR(255 CHAR),
"RECORD_DAY" INT DEFAULT 7,
"TRANSCODE_SUFFIX" VARCHAR(255 CHAR),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_MEDIA_SERVER_UNIQUE_IP_HTTP_PORT" UNIQUE("IP", "HTTP_PORT")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "dahuang-wvp-pro"."WVP_PLATFORM"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"ENABLE" TINYINT DEFAULT 0,
"NAME" VARCHAR(255 CHAR),
"SERVER_GB_ID" VARCHAR(50 CHAR),
"SERVER_GB_DOMAIN" VARCHAR(50 CHAR),
"SERVER_IP" VARCHAR(50 CHAR),
"SERVER_PORT" INT,
"DEVICE_GB_ID" VARCHAR(50 CHAR),
"DEVICE_IP" VARCHAR(50 CHAR),
"DEVICE_PORT" VARCHAR(50 CHAR),
"USERNAME" VARCHAR(255 CHAR),
"PASSWORD" VARCHAR(50 CHAR),
"EXPIRES" VARCHAR(50 CHAR),
"KEEP_TIMEOUT" VARCHAR(50 CHAR),
"TRANSPORT" VARCHAR(50 CHAR),
"CIVIL_CODE" VARCHAR(50 CHAR),
"MANUFACTURER" VARCHAR(255 CHAR),
"DB_MODEL" VARCHAR(255 CHAR),
"ADDRESS" VARCHAR(255 CHAR),
"CHARACTER_SET" VARCHAR(50 CHAR),
"PTZ" TINYINT DEFAULT 0,
"RTCP" TINYINT DEFAULT 0,
"STATUS" TINYINT DEFAULT 0,
"CATALOG_GROUP" INT,
"REGISTER_WAY" INT,
"SECRECY" INT,
"CREATE_TIME" VARCHAR(50 CHAR),
"UPDATE_TIME" VARCHAR(50 CHAR),
"AS_MESSAGE_CHANNEL" TINYINT DEFAULT 0,
"CATALOG_WITH_PLATFORM" INT DEFAULT 1,
"CATALOG_WITH_GROUP" INT DEFAULT 1,
"CATALOG_WITH_REGION" INT DEFAULT 1,
"AUTO_PUSH_CHANNEL" TINYINT DEFAULT 1,
"SEND_STREAM_IP" VARCHAR(50 CHAR),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_PLATFORM_UNIQUE_SERVER_GB_ID" UNIQUE("SERVER_GB_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 2;

CREATE TABLE "dahuang-wvp-pro"."WVP_PLATFORM_CHANNEL"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"PLATFORM_ID" INT,
"DEVICE_CHANNEL_ID" INT,
"CUSTOM_DEVICE_ID" VARCHAR(50 CHAR),
"CUSTOM_NAME" VARCHAR(255 CHAR),
"CUSTOM_MANUFACTURER" VARCHAR(50 CHAR),
"CUSTOM_MODEL" VARCHAR(50 CHAR),
"CUSTOM_OWNER" VARCHAR(50 CHAR),
"CUSTOM_CIVIL_CODE" VARCHAR(50 CHAR),
"CUSTOM_BLOCK" VARCHAR(50 CHAR),
"CUSTOM_ADDRESS" VARCHAR(50 CHAR),
"CUSTOM_PARENTAL" INT,
"CUSTOM_PARENT_ID" VARCHAR(50 CHAR),
"CUSTOM_SAFETY_WAY" INT,
"CUSTOM_REGISTER_WAY" INT,
"CUSTOM_CERT_NUM" VARCHAR(50 CHAR),
"CUSTOM_CERTIFIABLE" INT,
"CUSTOM_ERR_CODE" INT,
"CUSTOM_END_TIME" VARCHAR(50 CHAR),
"CUSTOM_SECRECY" INT,
"CUSTOM_IP_ADDRESS" VARCHAR(50 CHAR),
"CUSTOM_PORT" INT,
"CUSTOM_PASSWORD" VARCHAR(255 CHAR),
"CUSTOM_STATUS" VARCHAR(50 CHAR),
"CUSTOM_LONGITUDE" DOUBLE,
"CUSTOM_LATITUDE" DOUBLE,
"CUSTOM_PTZ_TYPE" INT,
"CUSTOM_POSITION_TYPE" INT,
"CUSTOM_ROOM_TYPE" INT,
"CUSTOM_USE_TYPE" INT,
"CUSTOM_SUPPLY_LIGHT_TYPE" INT,
"CUSTOM_DIRECTION_TYPE" INT,
"CUSTOM_RESOLUTION" VARCHAR(255 CHAR),
"CUSTOM_BUSINESS_GROUP_ID" VARCHAR(255 CHAR),
"CUSTOM_DOWNLOAD_SPEED" VARCHAR(255 CHAR),
"CUSTOM_SVC_SPACE_SUPPORT_MOD" INT,
"CUSTOM_SVC_TIME_SUPPORT_MODE" INT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_PLATFORM_GB_CHANNEL_PLATFORM_ID_CATALOG_ID_DEVICE_CHANNEL_ID" UNIQUE("PLATFORM_ID", "DEVICE_CHANNEL_ID"),
CONSTRAINT "UK_PLATFORM_GB_CHANNEL_DEVICE_ID" UNIQUE("CUSTOM_DEVICE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE TABLE "dahuang-wvp-pro"."WVP_PLATFORM_GROUP"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"PLATFORM_ID" INT,
"GROUP_ID" INT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_WVP_PLATFORM_GROUP_PLATFORM_ID_GROUP_ID" UNIQUE("PLATFORM_ID", "GROUP_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE TABLE "dahuang-wvp-pro"."WVP_PLATFORM_REGION"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"PLATFORM_ID" INT,
"REGION_ID" INT,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_WVP_PLATFORM_REGION_PLATFORM_ID_GROUP_ID" UNIQUE("PLATFORM_ID", "REGION_ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE TABLE "dahuang-wvp-pro"."WVP_RECORD_PLAN"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"SNAP" TINYINT DEFAULT 0,
"NAME" VARCHAR(255 CHAR) NOT NULL,
"CREATE_TIME" VARCHAR(50 CHAR),
"UPDATE_TIME" VARCHAR(50 CHAR),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 4;

CREATE TABLE "dahuang-wvp-pro"."WVP_RECORD_PLAN_ITEM"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"START" INT,
"STOP" INT,
"WEEK_DAY" INT,
"PLAN_ID" INT,
"CREATE_TIME" VARCHAR(50 CHAR),
"UPDATE_TIME" VARCHAR(50 CHAR),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 9;

CREATE TABLE "dahuang-wvp-pro"."WVP_RESOURCES_TREE"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"IS_CATALOG" TINYINT DEFAULT 1,
"DEVICE_CHANNEL_ID" INT,
"GB_STREAM_ID" INT,
"NAME" VARCHAR(255 CHAR),
"PARENTID" INT,
"PATH" VARCHAR(255 CHAR),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE TABLE "dahuang-wvp-pro"."WVP_SIP_CONFIG"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"IP" VARCHAR(255 CHAR),
"SHOW_IP" VARCHAR(255 CHAR),
"PORT" INT DEFAULT 8116 NOT NULL,
"GB_DOMAIN" VARCHAR(50 CHAR) DEFAULT '4101050000' NOT NULL,
"SERVER_ID" VARCHAR(50 CHAR) DEFAULT '41010500002000000001' NOT NULL,
"GB_PWD" VARCHAR(50 CHAR) DEFAULT '12345678',
"PTZ_SPEED" INT DEFAULT 50,
"REGISTER_TIME_INTERVAL" INT DEFAULT 120,
"ALARM" TINYINT DEFAULT 0,
"TIMEOUT" BIGINT DEFAULT 15,
"CREATE_TIME" VARCHAR(50 CHAR),
"UPDATE_TIME" VARCHAR(50 CHAR),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 2;

COMMENT ON TABLE "dahuang-wvp-pro".WVP_SIP_CONFIG IS 'SIP配置表';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."ALARM" IS '是否接收报警信息';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."GB_DOMAIN" IS '国标域';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."GB_PWD" IS '设备认证密码';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."ID" IS '主键ID';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."IP" IS 'SIP服务监听的IP地址，多个IP用逗号分隔';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."PORT" IS 'SIP服务监听的端口';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."PTZ_SPEED" IS '云台速度';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."REGISTER_TIME_INTERVAL" IS '注册时间间隔（秒）';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."SERVER_ID" IS '国标服务器ID';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."SHOW_IP" IS '对外展示的IP地址';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."TIMEOUT" IS '超时时间（秒）';
COMMENT ON COLUMN "dahuang-wvp-pro".WVP_SIP_CONFIG."UPDATE_TIME" IS '更新时间';


CREATE TABLE "dahuang-wvp-pro"."WVP_STREAM_PROXY"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"TYPE" VARCHAR(50 CHAR),
"APP" VARCHAR(255 CHAR),
"STREAM" VARCHAR(255 CHAR),
"SRC_URL" VARCHAR(255 CHAR),
"TIMEOUT" INT,
"FFMPEG_CMD_KEY" VARCHAR(255 CHAR),
"RTSP_TYPE" VARCHAR(50 CHAR),
"MEDIA_SERVER_ID" VARCHAR(50 CHAR),
"ENABLE_AUDIO" TINYINT DEFAULT 0,
"ENABLE_MP4" TINYINT DEFAULT 0,
"PULLING" TINYINT DEFAULT 0,
"ENABLE" TINYINT DEFAULT 0,
"ENABLE_REMOVE_NONE_READER" TINYINT DEFAULT 0,
"CREATE_TIME" VARCHAR(50 CHAR),
"NAME" VARCHAR(255 CHAR),
"UPDATE_TIME" VARCHAR(50 CHAR),
"STREAM_KEY" VARCHAR(255 CHAR),
"ENABLE_DISABLE_NONE_READER" TINYINT DEFAULT 0,
"RELATES_MEDIA_SERVER_ID" VARCHAR(50 CHAR),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_STREAM_PROXY_APP_STREAM" UNIQUE("APP", "STREAM")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE TABLE "dahuang-wvp-pro"."WVP_STREAM_PUSH"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"APP" VARCHAR(255 CHAR),
"STREAM" VARCHAR(255 CHAR),
"CREATE_TIME" VARCHAR(50 CHAR),
"MEDIA_SERVER_ID" VARCHAR(50 CHAR),
"SERVER_ID" VARCHAR(50 CHAR),
"PUSH_TIME" VARCHAR(50 CHAR),
"STATUS" TINYINT DEFAULT 0,
"UPDATE_TIME" VARCHAR(50 CHAR),
"PUSHING" TINYINT DEFAULT 0,
"SELF" TINYINT DEFAULT 0,
"START_OFFLINE_PUSH" TINYINT DEFAULT 1,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UK_STREAM_PUSH_APP_STREAM" UNIQUE("APP", "STREAM")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE TABLE "dahuang-wvp-pro"."WVP_USER_API_KEY"
(
"ID" BIGINT AUTO_INCREMENT NOT NULL,
"USER_ID" BIGINT,
"APP" VARCHAR(255 CHAR),
"API_KEY" TEXT,
"EXPIRED_AT" BIGINT,
"REMARK" VARCHAR(255 CHAR),
"ENABLE" TINYINT DEFAULT 1,
"CREATE_TIME" VARCHAR(50 CHAR),
"UPDATE_TIME" VARCHAR(50 CHAR),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 2;

